package org.Views;

import org.Controller.HelpRequestController;
import org.Model.Helprequest;

import com.google.protobuf.DescriptorProtos.MethodOptions.IdempotencyLevel;

import org.Controller.CustomDialog;
import org.Controller.DatabaseController;
import org.Controller.UserController;

import java.awt.Color;
import java.sql.SQLException;
import java.util.List;

import java.util.Date;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

public class MyMissions extends JFrame {

	/*
	 */

	private JPanel getContentPane;

	private JPanel panel_menu;
	private JLabel label_NameAPP;
	private JLabel Label_Welcome;
	private boolean homeButtonClicked;

	// PANEL LEFT
	private JPanel panel_left;

	private JTable TableRequest;
	private JButton btn_show_table_data;
	private JButton btn_Postulate;

	// PANEL RIGHT
	private JPanel panel_right;

	private JTable tableVolunteerMissions;
	


	public MyMissions(String user) throws ClassNotFoundException, SQLException {
		initComponents(user);
		setVisible(true);
		// errorOptionPane = new JOptionPane();
	}
	


	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * @throws SQLException 
	 * @throws ClassNotFoundException 
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents(String user) throws ClassNotFoundException, SQLException {

		// Creacion Main Panel
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 1200, 700);
		getContentPane = new JPanel();
		getContentPane().setBackground(Color.LIGHT_GRAY);
		getContentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(getContentPane);
		getContentPane.setLayout(null);

		// PANEL MENU
		panel_menu = new JPanel();
		panel_menu.setBackground(new Color(0, 128, 128));
		panel_menu.setLayout(null);
		panel_menu.setBorder(new EmptyBorder(5, 5, 5, 5));
		// contentPane_Left.setBackground(new Color(0, 128, 128));
		panel_menu.setBounds(0, 0, 1200, 150);
		getContentPane().add(panel_menu);

		label_NameAPP = new JLabel("VULNERABLES");
        label_NameAPP.setForeground(new Color(255, 255, 255));
        label_NameAPP.setHorizontalAlignment(SwingConstants.CENTER);
        label_NameAPP.setFont(new Font("Lucida Grande", Font.BOLD, 30));
        label_NameAPP.setBounds(450, 50, 300, 50);
        panel_menu.add(label_NameAPP);

        //String FirstName = connexion.getName(email.getText(), passwordString);
        Label_Welcome = new JLabel("Welcome, " + user);
        Label_Welcome.setForeground(Color.WHITE);
        Label_Welcome.setBounds(45, 90, 200, 50);
        Label_Welcome.setFont(new Font("Lucida Grande", Font.BOLD, 15));
        panel_menu.add(Label_Welcome);

        JButton btn_Home = new JButton();
        btn_Home.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		VHelprequest homePage = new VHelprequest(user);
        		homePage.setVisible(true);
        		homeButtonClicked = true;
           		MyMissions.this.dispose();
           		System.out.println("you have change To Sign Up");
        	}
        });
        btn_Home.setBounds(823, 96, 100, 40);
        panel_menu.add(btn_Home);
        btn_Home.setText("Home");
        btn_Home.setFont(new Font("Lucida Grande", Font.PLAIN, 14));
        btn_Home.setBackground(new Color(0, 204, 0));



        JButton btn_Missions = new JButton();
        btn_Missions.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        btn_Missions.setText("Missions");
        btn_Missions.setFont(new Font("Lucida Grande", Font.PLAIN, 14));
        btn_Missions.setBackground(new Color(0, 204, 0));
        btn_Missions.setBounds(962, 96, 100, 40);
        panel_menu.add(btn_Missions);


		// LEFT PANEL
		panel_left = new JPanel();
		panel_left.setBackground(Color.LIGHT_GRAY);
		panel_left.setLayout(null);
		panel_left.setBorder(new EmptyBorder(5, 5, 5, 5));
		panel_left.setBounds(0, 150, 600, 500);
		getContentPane().add(panel_left);


		// Column names
        String[] columnNames = {"ID" ,"Title", "Date", "Description", "Statut", "Volunteer"};

        // Data for the table in a 2D array
        Object[][] data = {
            // ... you can add more rows as needed
        };

		// Create a table with the data and column names
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
		TableRequest = new JTable(model);
		TableRequest.setFillsViewportHeight(true);
		JScrollPane scrollPane = new JScrollPane(TableRequest);
		scrollPane.setBounds(40, 20, 520, 300);
		panel_left.add(scrollPane);


		btn_show_table_data = new JButton();
		btn_show_table_data.setBackground(new java.awt.Color(0, 204, 0));
		btn_show_table_data.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
		btn_show_table_data.setText("Show Waiting Requests");
		btn_show_table_data.setBounds(100, 375, 200, 50);
		panel_left.add(btn_show_table_data);
		btn_show_table_data.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					show_table_dataActionPerformed(evt);
				} catch (SQLException e) {
					throw new RuntimeException(e);
				} catch (ClassNotFoundException e) {
					throw new RuntimeException(e);
				}
			}
		});


		btn_Postulate = new JButton();
		btn_Postulate.setBackground(new java.awt.Color(0, 204, 0));
		btn_Postulate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
		btn_Postulate.setText("Postulate");
		btn_Postulate.setBounds(350, 375, 150, 50);
		panel_left.add(btn_Postulate);
		btn_Postulate.addActionListener(new ActionListener() {
		    public void actionPerformed(ActionEvent e) {
		        int selectedRow = TableRequest.getSelectedRow();
		        if (selectedRow >= 0) {
		            int requestId = Integer.parseInt(TableRequest.getValueAt(selectedRow, 0).toString());
		            System.out.println(requestId +" "+ user);
		            HelpRequestController controller = null;
		            try {
		            	controller = new HelpRequestController();
		                controller.assignVolunteerToRequest(requestId, user); // Método ficticio, necesitas implementarlo
		                JOptionPane.showMessageDialog(MyMissions.this, "You have been assigned as volunteer", "Success", JOptionPane.INFORMATION_MESSAGE);
						show_table_dataActionPerformed(e);
						fillVolunteerMissions(user);
		            } catch (Exception ex) {
		                JOptionPane.showMessageDialog(MyMissions.this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		                ex.printStackTrace();
		            }
		        } else {
		            JOptionPane.showMessageDialog(MyMissions.this, "Please select a request to postulate for", "Error", JOptionPane.WARNING_MESSAGE);
		        }
		    }
		});
		panel_left.add(btn_Postulate);


		// RIGHT PANEL
		panel_right = new JPanel();
		panel_right.setBackground(Color.LIGHT_GRAY);
		panel_right.setLayout(null);
		panel_right.setBorder(new EmptyBorder(5, 5, 5, 5));
		// contentPane_Right.setBackground(Color.LIGHT_GRAY);
		panel_right.setBounds(600, 150, 600, 500);
		getContentPane().add(panel_right);


		String[] ColumnNames = {"ID", "Title", "Date", "Description", "Status"};
		Object[][] data2 = {
	            // ... you can add more rows as needed
	        };
		DefaultTableModel volunteerModel = new DefaultTableModel(data2, ColumnNames);
		tableVolunteerMissions = new JTable(volunteerModel);
		tableVolunteerMissions.setFillsViewportHeight(true);
		JScrollPane volunteerScrollPane = new JScrollPane(tableVolunteerMissions);
		volunteerScrollPane.setBounds(30, 20, 520, 200); // Ajusta las dimensiones según tus necesidades
		panel_right.add(volunteerScrollPane);

		// Llena la tabla con misiones voluntarias
		fillVolunteerMissions(user);



	}

	private void fillVolunteerMissions(String volunteerName) throws ClassNotFoundException, SQLException {
	    HelpRequestController controller = new HelpRequestController();
	    List<Helprequest> missions = controller.getVolunteerRequests(volunteerName);
	    DefaultTableModel model = (DefaultTableModel) tableVolunteerMissions.getModel();
	    model.setRowCount(0); // Limpiar la tabla antes de añadir nuevas filas

	    for (Helprequest hr : missions) {
	        model.addRow(new Object[]{
	            hr.getID(),
	            hr.getTitle(),
	            hr.getDate(),
	            hr.getDescription(),
	            hr.getStatus()
	        });
	    }
	}

	
	// SHOW ALL REQUEST 
	private void show_table_dataActionPerformed(java.awt.event.ActionEvent evt)
			throws SQLException, ClassNotFoundException {// GEN-FIRST:event_show_table_dataActionPerformed
		// TODO add your handling code here:
		HelpRequestController connexion = new HelpRequestController();
		DefaultTableModel tb1Model = (DefaultTableModel) TableRequest.getModel();
		// Vider la table avant d'exécuter la mise à jour
		tb1Model.setRowCount(0);
		List<Helprequest> helprequestList = connexion.getWaitingRequests();

		for (Helprequest hr : helprequestList) {
			String tdData[] = {String.valueOf(hr.getID()), hr.getTitle(), hr.getDate().toString(), hr.getDescription(), hr.getStatus(), hr.getVolunteer() };
			tb1Model.addRow(tdData);
		}
	}
}